#!/usr/bin/env python

# This file is Copyright 2010 Dean Hall.
# This file is part of the Python-on-a-Chip tools.
# This software is licensed under the MIT License.
# See the LICENSE file for details.

"""
Generates C definitions on stdout for all features in the input set to True

Expects name of a pmfeatures.py file as the only argument.
"""


import sys, time


execfile(sys.argv[1])
sys.stdout.write("/* Automatically generated by %s on %s.  DO NOT EDIT. */\n"
                 % (sys.argv[0], time.ctime(time.time())))
map(sys.stdout.write,
    ("#define %s\n" % s for s in PM_FEATURES.keys() if PM_FEATURES[s]))
